# Generated by Django 5.2.3 on 2025-06-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('college', '대학생'), ('sports', '스포츠'), ('idol', '아이돌'), ('custom', '사용자 정의')], max_length=20)),
                ('content', models.TextField()),
            ],
        ),
    ]
