# Generated by Django 5.2.3 on 2025-06-19 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.question')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gameroom')),
            ],
        ),
    ]
