# Generated by Django 5.2.3 on 2025-06-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinroom',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
