# Generated by Django 5.2.3 on 2025-06-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_playerinroom_is_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerinroom',
            name='user',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='current_turn_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerinroom',
            name='drink_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerinroom',
            name='nickname',
            field=models.CharField(default='익명', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
