# Generated by Django 5.2.3 on 2025-06-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_playerinroom_user_gameroom_current_turn_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='current_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='playerinroom',
            name='nickname',
            field=models.CharField(default='익명', max_length=30),
        ),
    ]
