# Generated by Django 5.2.3 on 2025-06-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_gameroom_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='result_image/'),
        ),
    ]
