# Generated by Django 5.2.3 on 2025-06-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_playerinroom_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerinroom',
            name='image',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='result_image/'),
        ),
    ]
