# Generated by Django 5.2.3 on 2025-06-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_playerinroom_image_gameroom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='zone',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
