# Generated by Django 5.2.3 on 2025-06-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_question_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='zone',
        ),
    ]
